python  DTW.py --dataset ArticularyWordRecognition  --path UEA  --seed 0 
python  DTW.py --dataset LSST --path UEA  --seed 0 
python  DTW.py --dataset PenDigits --path UEA  --seed 0 
python  DTW.py --dataset StandWalkJump --path UEA  --seed 0 
python  DTW.py --dataset InsectWingbeat --path UEA  --seed 0 
python  DTW.py --dataset ArticularyWordRecognition  --path UEA  --seed 1 
python  DTW.py --dataset LSST --path UEA  --seed 1 
python  DTW.py --dataset PenDigits --path UEA  --seed 1 
python  DTW.py --dataset StandWalkJump --path UEA  --seed 1 
python  DTW.py --dataset InsectWingbeat --path UEA  --seed 1 
python  DTW.py --dataset ArticularyWordRecognition  --path UEA  --seed 2 
python  DTW.py --dataset LSST --path UEA  --seed 2
python  DTW.py --dataset PenDigits --path UEA  --seed 2 
python  DTW.py --dataset StandWalkJump --path UEA  --seed 2 
python  DTW.py --dataset InsectWingbeat --path UEA  --seed 2 
python  DTW.py --dataset ArticularyWordRecognition  --path UEA  --seed 3 
python  DTW.py --dataset LSST --path UEA  --seed 3
python  DTW.py --dataset PenDigits --path UEA  --seed 3 
python  DTW.py --dataset StandWalkJump --path UEA  --seed 3 
python  DTW.py --dataset InsectWingbeat --path UEA  --seed 3 
python  DTW.py --dataset ArticularyWordRecognition  --path UEA  --seed 42
python  DTW.py --dataset LSST --path UEA  --seed 42
python  DTW.py --dataset PenDigits --path UEA  --seed 42 
python  DTW.py --dataset StandWalkJump --path UEA  --seed 42 
python  DTW.py --dataset InsectWingbeat --path UEA  --seed 42 
