
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset Strawberry --batchsize 16
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 10 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset SwedishLeaf --batchsize 8
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset Symbols --batchsize 16
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset ToeSegmentation1 --batchsize 16
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset ToeSegmentation2 --batchsize 4
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset Trace --batchsize 4
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 300 --epochs_down 100 --loss rank --dataset TwoLeadECG --batchsize 4
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5  --seed 42  --weight_decay 0.0005  --lr 0.0001   --epochs_up 100 --epochs_down 100 --loss rank --dataset TwoPatterns --batchsize 4
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 10  --seed 42  --weight_decay 0.0005 --lr 0.0001   --epochs_up 100 --epochs_down 100 --loss rank --dataset UMD --batchsize 4
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5  --seed 42  --weight_decay 0.0005  --lr 0.0001   --epochs_up 300 --epochs_down 100 --loss rank --dataset Wine --batchsize 8
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5  --seed 42  --weight_decay 0.0005  --lr 0.0001   --epochs_up 300 --epochs_down 100 --loss rank --dataset WordSynonyms --batchsize 8
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset Worms --batchsize 16
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset  WormsTwoClass --batchsize 4
python Rank_loss_norm_model.py --path UCR --cuda --device 3 --model FCN --distance EU --aug_positives 5 --seed 42  --weight_decay 0.0005 --lr 0.0001 --epochs_up 100 --epochs_down 100 --loss rank --dataset Yoga --batchsize 16
