python  -m tnc.tnc --dataset Chinatown --path UCR    --seed 42 --batchsize 16 --cv 1 
python  -m evaluations.classification_test --dataset Chinatown --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SonyAIBORobotSurface1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset SonyAIBORobotSurface1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ItalyPowerDemand --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ItalyPowerDemand --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset MoteStrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset MoteStrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SonyAIBORobotSurface2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset SonyAIBORobotSurface2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset TwoLeadECG --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset TwoLeadECG --path UCR   --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SmoothSubspace --path UCR    --seed 42 --batchsize 16 --cv 1 
python  -m evaluations.classification_test --dataset SmoothSubspace --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ECGFiveDays --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ECGFiveDays --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Fungi --path UCR    --seed 42 --batchsize 16 --cv 1 
python  -m evaluations.classification_test --dataset Fungi --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset CBF --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset CBF --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset BME --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset BME --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset UMD --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset UMD --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset DiatomSizeReduction --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset DiatomSizeReduction --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset DodgerLoopWeekend --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset DodgerLoopWeekend --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset DodgerLoopGame --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset DodgerLoopGame --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GunPoint --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset GunPoint --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Coffee --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Coffee --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset FaceFour --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset FaceFour --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset FreezerSmallTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset FreezerSmallTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ArrowHead --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ArrowHead --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ECG200 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ECG200 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Symbols --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Symbols --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ShapeletSim --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ShapeletSim --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset InsectEPGSmallTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset InsectEPGSmallTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset BeetleFly --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset BeetleFly --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset BirdChicken --path UCR    --seed 42 --batchsize 16 --cv 1 
python  -m evaluations.classification_test --dataset BirdChicken --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ToeSegmentation1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ToeSegmentation1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ToeSegmentation2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ToeSegmentation2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Wine --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Wine --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Beef --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Beef --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Plane --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Plane --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset OliveOil --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset OliveOil --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SyntheticControl --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset SyntheticControl --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset PickupGestureWiimoteZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset PickupGestureWiimoteZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ShakeGestureWiimoteZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ShakeGestureWiimoteZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GunPointMaleVersusFemale --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset GunPointMaleVersusFemale --path UCR   --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GunPointAgeSpan --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset GunPointAgeSpan --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GunPointOldVersusYoung --path UCR    --seed 42 --batchsize 16 --cv 1 
python  -m evaluations.classification_test --dataset GunPointOldVersusYoung --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Lightning7 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Lightning7 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset DodgerLoopDay --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset DodgerLoopDay --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset PowerCons --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset PowerCons --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Faces--path UCR  --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Faces--path UCR  --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Meat --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Meat --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Trace --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Trace --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset MelbournePedestrian --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset MelbournePedestrian --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset MiddlePhalanxTW --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset MiddlePhalanxTW --path UCR   --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset DistalPhalanxOutlineAgeGroup --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset DistalPhalanxOutlineAgeGroup --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset MiddlePhalanxOutlineAgeGroup --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset MiddlePhalanxOutlineAgeGroup --path UCR   --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ProximalPhalanxTW --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ProximalPhalanxTW --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ProximalPhalanxOutlineAgeGroup --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ProximalPhalanxOutlineAgeGroup --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset DistalPhalanxTW --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset DistalPhalanxTW --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Herring --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Herring --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Car --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Car --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset InsectEPGRegularTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset InsectEPGRegularTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset MedicalImages --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset MedicalImages --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Lightning2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Lightning2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset FreezerRegularTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset FreezerRegularTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Ham --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Ham --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset MiddlePhalanxOutlineCorrect --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset MiddlePhalanxOutlineCorrect --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset DistalPhalanxOutlineCorrect --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset DistalPhalanxOutlineCorrect --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ProximalPhalanxOutlineCorrect --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ProximalPhalanxOutlineCorrect --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Mallat --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Mallat --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset InsectWingbeatSound --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset InsectWingbeatSound --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Rock --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Rock --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GesturePebbleZ1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset GesturePebbleZ1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SwedishLeaf --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset SwedishLeaf --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset CinCECGTorso --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset CinCECGTorso --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GesturePebbleZ2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset GesturePebbleZ2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Adiac --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Adiac --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ECG5000 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ECG5000 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset WordSynonyms --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset WordSynonyms --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset FaceAll --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset FaceAll --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GestureMidAirD2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset GestureMidAirD2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GestureMidAirD3 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset GestureMidAirD3 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset GestureMidAirD1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset GestureMidAirD1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ChlorineConcentration --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ChlorineConcentration --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset HouseTwenty --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset HouseTwenty --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Fish --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Fish --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset OSULeaf --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset OSULeaf --path UCR   --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset MixedShapesSmallTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset MixedShapesSmallTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset CricketZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset CricketZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset CricketX --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset CricketX --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset CricketY --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset CricketY --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset FiftyWords --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset FiftyWords --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Yoga --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Yoga --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset TwoPatterns --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset TwoPatterns --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset PhalangesOutlinesCorrect --path UCR    --seed 42 --batchsize 16 --cv 1 
python  -m evaluations.classification_test --dataset PhalangesOutlinesCorrect --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Strawberry --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Strawberry --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ACSF1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ACSF1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset AllGestureWiimoteY --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset AllGestureWiimoteY --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset AllGestureWiimoteX --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset AllGestureWiimoteX --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset AllGestureWiimoteZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset AllGestureWiimoteZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Wafer --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Wafer --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset WormsTwoClass --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset WormsTwoClass --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Worms --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Worms --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Earthquakes --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Earthquakes --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Haptics --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Haptics --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Computers --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Computers --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset InlineSkate --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset InlineSkate --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset PigArtPressure --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset PigArtPressure --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset PigCVP --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset PigCVP --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset PigAirwayPressure --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset PigAirwayPressure --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Phoneme --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Phoneme --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ScreenType --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ScreenType --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset LargeKitchenAppliances --path UCR    --seed 42 --batchsize 16 --cv 1 
python  -m evaluations.classification_test --dataset LargeKitchenAppliances --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SmallKitchenAppliances --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset SmallKitchenAppliances --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset RefrigerationDevices --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset RefrigerationDevices --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset UWaveGestureLibraryZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset UWaveGestureLibraryZ --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset UWaveGestureLibraryY --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset UWaveGestureLibraryY --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset UWaveGestureLibraryX --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset UWaveGestureLibraryX --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ShapesAll --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ShapesAll --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset Crop --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset Crop --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SemgHandGenderCh2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset SemgHandGenderCh2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset EOGVerticalSignal --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset EOGVerticalSignal --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset EOGHorizontalSignal --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset EOGHorizontalSignal --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset MixedShapesRegularTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset MixedShapesRegularTrain --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SemgHandMovementCh2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset SemgHandMovementCh2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset SemgHandSubjectCh2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset SemgHandSubjectCh2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset PLAID --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset PLAID --path UCR   --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset UWaveGestureLibraryAll --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset UWaveGestureLibraryAll --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset ElectricDevices --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset ElectricDevices --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset EthanolLevel --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset EthanolLevel --path UCR   --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset StarLightCurves --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset StarLightCurves --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset NonInvasiveFetalECGThorax1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset NonInvasiveFetalECGThorax1 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset NonInvasiveFetalECGThorax2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset NonInvasiveFetalECGThorax2 --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset FordA --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset FordA --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m tnc.tnc --dataset FordB --path UCR    --seed 42 --batchsize 16 --cv 1  
python  -m evaluations.classification_test --dataset FordB --path UCR    --seed 42 --batchsize 16 --cv 1  

